/**
 * Registry mapping Helix command names (as used in the keymap) to implementations.
 */
import { Engine } from '../engine';
import { CommandFn } from '../types';
import * as mv from './movement';
import * as sel from './selection';
import * as ch from './changes';
import * as se from './search';
import * as ma from './match';
import * as un from './unimpaired';
import * as vw from './view';
import * as sh from './shell';
import * as ins from './insert';
import { gotoWord, extendToWord } from '../../vscode/labels';

type Table = Record<string, [string, CommandFn]>;

export function registerCommands(engine: Engine): void {
  const table: Table = {
    // ---- movement ----
    move_char_left: ['Move left', mv.moveCharLeft],
    move_char_right: ['Move right', mv.moveCharRight],
    move_line_up: ['Move up', mv.moveLineUp],
    move_line_down: ['Move down', mv.moveLineDown],
    move_visual_line_up: ['Move up (visual line)', mv.moveVisualLineUp],
    move_visual_line_down: ['Move down (visual line)', mv.moveVisualLineDown],
    extend_char_left: ['Extend left', mv.extendCharLeft],
    extend_char_right: ['Extend right', mv.extendCharRight],
    extend_line_up: ['Extend up', mv.extendLineUp],
    extend_line_down: ['Extend down', mv.extendLineDown],
    extend_visual_line_up: ['Extend up (visual line)', mv.extendVisualLineUp],
    extend_visual_line_down: ['Extend down (visual line)', mv.extendVisualLineDown],
    move_next_word_start: ['Move to start of next word', mv.moveNextWordStart],
    move_prev_word_start: ['Move to start of previous word', mv.movePrevWordStart],
    move_next_word_end: ['Move to end of next word', mv.moveNextWordEnd],
    move_prev_word_end: ['Move to end of previous word', mv.movePrevWordEnd],
    move_next_long_word_start: ['Move to start of next long word', mv.moveNextLongWordStart],
    move_prev_long_word_start: ['Move to start of previous long word', mv.movePrevLongWordStart],
    move_next_long_word_end: ['Move to end of next long word', mv.moveNextLongWordEnd],
    move_prev_long_word_end: ['Move to end of previous long word', mv.movePrevLongWordEnd],
    move_next_sub_word_start: ['Move to start of next sub word', mv.moveNextSubWordStart],
    move_prev_sub_word_start: ['Move to start of previous sub word', mv.movePrevSubWordStart],
    move_next_sub_word_end: ['Move to end of next sub word', mv.moveNextSubWordEnd],
    move_prev_sub_word_end: ['Move to end of previous sub word', mv.movePrevSubWordEnd],
    extend_next_word_start: ['Extend to start of next word', mv.extendNextWordStart],
    extend_prev_word_start: ['Extend to start of previous word', mv.extendPrevWordStart],
    extend_next_word_end: ['Extend to end of next word', mv.extendNextWordEnd],
    extend_prev_word_end: ['Extend to end of previous word', mv.extendPrevWordEnd],
    extend_next_long_word_start: ['Extend to start of next long word', mv.extendNextLongWordStart],
    extend_prev_long_word_start: ['Extend to start of previous long word', mv.extendPrevLongWordStart],
    extend_next_long_word_end: ['Extend to end of next long word', mv.extendNextLongWordEnd],
    extend_prev_long_word_end: ['Extend to end of previous long word', mv.extendPrevLongWordEnd],
    extend_next_sub_word_start: ['Extend to start of next sub word', mv.extendNextSubWordStart],
    extend_prev_sub_word_start: ['Extend to start of previous sub word', mv.extendPrevSubWordStart],
    extend_next_sub_word_end: ['Extend to end of next sub word', mv.extendNextSubWordEnd],
    extend_prev_sub_word_end: ['Extend to end of previous sub word', mv.extendPrevSubWordEnd],
    find_till_char: ['Move till next occurrence of char', mv.findTillChar],
    find_next_char: ['Move to next occurrence of char', mv.findNextChar],
    till_prev_char: ['Move till previous occurrence of char', mv.tillPrevChar],
    find_prev_char: ['Move to previous occurrence of char', mv.findPrevChar],
    extend_till_char: ['Extend till next occurrence of char', mv.extendTillChar],
    extend_next_char: ['Extend to next occurrence of char', mv.extendNextChar],
    extend_till_prev_char: ['Extend till previous occurrence of char', mv.extendTillPrevChar],
    extend_prev_char: ['Extend to previous occurrence of char', mv.extendPrevChar],
    repeat_last_motion: ['Repeat last motion', mv.repeatLastMotion],
    goto_line_start: ['Goto line start', mv.gotoLineStart],
    goto_line_end: ['Goto line end', mv.gotoLineEnd],
    goto_line_end_newline: ['Goto newline at line end', mv.gotoLineEndNewline],
    extend_to_line_start: ['Extend to line start', mv.extendToLineStart],
    extend_to_line_end: ['Extend to line end', mv.extendToLineEnd],
    goto_first_nonwhitespace: ['Goto first non-blank in line', mv.gotoFirstNonwhitespace],
    extend_to_first_nonwhitespace: ['Extend to first non-blank in line', mv.extendToFirstNonwhitespace],
    goto_column: ['Goto column', mv.gotoColumn],
    extend_to_column: ['Extend to column', mv.extendToColumn],
    goto_line: ['Goto line', mv.gotoLine],
    goto_file_start: ['Goto line number <n> else file start', mv.gotoFileStart],
    extend_to_file_start: ['Extend to line number <n> else file start', mv.extendToFileStart],
    goto_file_end: ['Goto file end', mv.gotoFileEnd],
    goto_last_line: ['Goto last line', mv.gotoLastLine],
    extend_to_last_line: ['Extend to last line', mv.extendToLastLine],
    goto_window_top: ['Goto window top', mv.gotoWindowTop],
    goto_window_center: ['Goto window center', mv.gotoWindowCenter],
    goto_window_bottom: ['Goto window bottom', mv.gotoWindowBottom],
    page_up: ['Move page up', mv.pageUp],
    page_down: ['Move page down', mv.pageDown],
    page_cursor_up: ['Move page and cursor up', mv.pageCursorUp],
    page_cursor_down: ['Move page and cursor down', mv.pageCursorDown],
    page_cursor_half_up: ['Move page and cursor half up', mv.pageCursorHalfUp],
    page_cursor_half_down: ['Move page and cursor half down', mv.pageCursorHalfDown],
    scroll_up: ['Scroll view up', mv.scrollUp],
    scroll_down: ['Scroll view down', mv.scrollDown],
    goto_prev_paragraph: ['Goto previous paragraph', mv.gotoPrevParagraph],
    goto_next_paragraph: ['Goto next paragraph', mv.gotoNextParagraph],
    jump_forward: ['Jump forward on jumplist', mv.jumpForward],
    jump_backward: ['Jump backward on jumplist', mv.jumpBackward],
    save_selection: ['Save current selection to jumplist', mv.saveSelection],
    goto_next_buffer: ['Goto next buffer', mv.gotoNextBuffer],
    goto_previous_buffer: ['Goto previous buffer', mv.gotoPreviousBuffer],
    goto_last_accessed_file: ['Goto last accessed file', mv.gotoLastAccessedFile],
    goto_last_modified_file: ['Goto last modified file', mv.gotoLastModifiedFile],
    goto_last_modification: ['Goto last modification', mv.gotoLastModification],
    goto_file: ['Goto files/URLs in selections', mv.gotoFile],
    goto_word: ['Jump to a two-character label', gotoWord],
    extend_to_word: ['Extend to a two-character label', extendToWord],
    suspend: ['Suspend and return to shell', mv.suspend],
    normal_mode: ['Enter normal mode', mv.normalModeCmd],
    select_mode: ['Enter selection extend mode', mv.selectModeCmd],
    exit_select_mode: ['Exit selection mode', mv.exitSelectModeCmd],

    // ---- selection ----
    select_all: ['Select whole document', sel.selectAll],
    collapse_selection: ['Collapse selection into single cursor', sel.collapseSelection],
    flip_selections: ['Flip selection cursor and anchor', sel.flipSelections],
    ensure_selections_forward: ['Ensure all selections face forward', sel.ensureSelectionsForward],
    keep_primary_selection: ['Keep primary selection', sel.keepPrimarySelection],
    remove_primary_selection: ['Remove primary selection', sel.removePrimarySelection],
    rotate_selections_forward: ['Rotate selections forward', sel.rotateSelectionsForward],
    rotate_selections_backward: ['Rotate selections backward', sel.rotateSelectionsBackward],
    rotate_selection_contents_forward: ['Rotate selection contents forward', sel.rotateSelectionContentsForward],
    rotate_selection_contents_backward: ['Rotate selections contents backward', sel.rotateSelectionContentsBackward],
    merge_selections: ['Merge selections', sel.mergeSelections],
    merge_consecutive_selections: ['Merge consecutive selections', sel.mergeConsecutiveSelections],
    split_selection_on_newline: ['Split selection on newlines', sel.splitSelectionOnNewline],
    trim_selections: ['Trim whitespace from selections', sel.trimSelections],
    extend_line: ['Select current line, if already selected, extend to another line based on the anchor', sel.extendLine],
    extend_line_below: ['Select current line, if already selected, extend to next line', sel.extendLineBelow],
    extend_line_above: ['Select current line, if already selected, extend to previous line', sel.extendLineAbove],
    extend_to_line_bounds: ['Extend selection to line bounds', sel.extendToLineBounds],
    shrink_to_line_bounds: ['Shrink selection to line bounds', sel.shrinkToLineBounds],
    copy_selection_on_next_line: ['Copy selection on next line', sel.copySelectionOnNextLine],
    copy_selection_on_prev_line: ['Copy selection on previous line', sel.copySelectionOnPrevLine],
    align_selections: ['Align selections in column', sel.alignSelections],

    // ---- changes ----
    insert_mode: ['Insert before selection', ch.insertMode],
    append_mode: ['Append after selection', ch.appendMode],
    insert_at_line_start: ['Insert at start of line', ch.insertAtLineStart],
    insert_at_line_end: ['Insert at end of line', ch.insertAtLineEnd],
    open_below: ['Open new line below selection', ch.openBelow],
    open_above: ['Open new line above selection', ch.openAbove],
    delete_selection: ['Delete selection', ch.deleteSelection],
    delete_selection_noyank: ['Delete selection without yanking', ch.deleteSelectionNoyank],
    change_selection: ['Change selection', ch.changeSelection],
    change_selection_noyank: ['Change selection without yanking', ch.changeSelectionNoyank],
    yank: ['Yank selection', ch.yank],
    yank_joined: ['Join and yank selections', ch.yankJoined],
    yank_to_clipboard: ['Yank selections to clipboard', ch.yankToClipboard],
    yank_joined_to_clipboard: ['Join and yank selections to clipboard', ch.yankJoinedToClipboard],
    yank_main_selection_to_clipboard: ['Yank main selection to clipboard', ch.yankMainSelectionToClipboard],
    paste_after: ['Paste after selection', ch.pasteAfter],
    paste_before: ['Paste before selection', ch.pasteBefore],
    paste_clipboard_after: ['Paste clipboard after selections', ch.pasteClipboardAfter],
    paste_clipboard_before: ['Paste clipboard before selections', ch.pasteClipboardBefore],
    replace_with_yanked: ['Replace with yanked text', ch.replaceWithYanked],
    replace_selections_with_clipboard: ['Replace selections by clipboard content', ch.replaceSelectionsWithClipboard],
    insert_register: ['Insert register', ch.insertRegister],
    replace: ['Replace with new char', ch.replace],
    switch_case: ['Switch (toggle) case', ch.switchCase],
    switch_to_lowercase: ['Switch to lowercase', ch.switchToLowercase],
    switch_to_uppercase: ['Switch to uppercase', ch.switchToUppercase],
    indent: ['Indent selection', ch.indent],
    unindent: ['Unindent selection', ch.unindent],
    format_selections: ['Format selection', ch.formatSelections],
    join_selections: ['Join lines inside selection', ch.joinSelections],
    join_selections_space: ['Join lines inside selection and select spaces', ch.joinSelectionsSpace],
    increment: ['Increment item under cursor', ch.incrementCmd],
    decrement: ['Decrement item under cursor', ch.decrementCmd],
    add_newline_above: ['Add newline above', ch.addNewlineAbove],
    add_newline_below: ['Add newline below', ch.addNewlineBelow],
    undo: ['Undo change', ch.undo],
    redo: ['Redo change', ch.redo],
    earlier: ['Move backward in history', ch.undo],
    later: ['Move forward in history', ch.redo],
    commit_undo_checkpoint: ['Commit changes to new checkpoint', ch.commitUndoCheckpoint],
    record_macro: ['Record macro', ch.recordMacro],
    replay_macro: ['Replay macro', ch.replayMacro],
    select_register: ['Select register', ch.selectRegister],

    // ---- search ----
    search: ['Search for regex pattern', se.searchCmd],
    rsearch: ['Reverse search for regex pattern', se.rsearch],
    search_next: ['Select next search match', se.searchNextCmd],
    search_prev: ['Select previous search match', se.searchPrev],
    extend_search_next: ['Add next search match to selection', se.extendSearchNext],
    extend_search_prev: ['Add previous search match to selection', se.extendSearchPrev],
    search_selection: ['Use current selection as the search pattern', se.searchSelection],
    search_selection_detect_word_boundaries: ['Use current selection as the search pattern, automatically wrapping with `\\b` on word boundaries', se.searchSelectionDetectWordBoundaries],
    select_regex: ['Select all regex matches inside selections', se.selectRegex],
    split_selection: ['Split selections on regex matches', se.splitSelection],
    keep_selections: ['Keep selections matching regex', se.keepSelections],
    remove_selections: ['Remove selections matching regex', se.removeSelections],
    global_search: ['Global search in workspace folder', se.globalSearch],

    // ---- match ----
    match_brackets: ['Goto matching bracket', ma.matchBrackets],
    surround_add: ['Surround add', ma.surroundAdd],
    surround_replace: ['Surround replace', ma.surroundReplace],
    surround_delete: ['Surround delete', ma.surroundDelete],
    select_textobject_around: ['Select around object', ma.selectTextobjectAround],
    select_textobject_inner: ['Select inside object', ma.selectTextobjectInner],
    expand_selection: ['Expand selection to parent syntax node', ma.expandSelection],
    shrink_selection: ['Shrink selection to previously expanded syntax node', ma.shrinkSelection],
    select_next_sibling: ['Select next sibling in the syntax tree', ma.selectNextSibling],
    select_prev_sibling: ['Select previous sibling the in syntax tree', ma.selectPrevSibling],
    select_all_siblings: ['Select all siblings of the current node', ma.selectAllSiblings],
    select_all_children: ['Select all children of the current node', ma.selectAllChildren],
    move_parent_node_end: ['Move to end of the parent node', ma.moveParentNodeEnd],
    move_parent_node_start: ['Move to beginning of the parent node', ma.moveParentNodeStart],
    extend_parent_node_end: ['Extend to end of the parent node', ma.extendParentNodeEnd],
    extend_parent_node_start: ['Extend to beginning of the parent node', ma.extendParentNodeStart],

    // ---- unimpaired ----
    goto_next_diag: ['Goto next diagnostic', un.gotoNextDiag],
    goto_prev_diag: ['Goto previous diagnostic', un.gotoPrevDiag],
    goto_first_diag: ['Goto first diagnostic', un.gotoFirstDiag],
    goto_last_diag: ['Goto last diagnostic', un.gotoLastDiag],
    goto_next_change: ['Goto next change', un.gotoNextChange],
    goto_prev_change: ['Goto previous change', un.gotoPrevChange],
    goto_first_change: ['Goto first change', un.gotoFirstChange],
    goto_last_change: ['Goto last change', un.gotoLastChange],
    goto_next_function: ['Goto next function', un.gotoNextFunction],
    goto_prev_function: ['Goto previous function', un.gotoPrevFunction],
    goto_next_class: ['Goto next type definition', un.gotoNextClass],
    goto_prev_class: ['Goto previous type definition', un.gotoPrevClass],
    goto_next_parameter: ['Goto next parameter', un.gotoNextParameter],
    goto_prev_parameter: ['Goto previous parameter', un.gotoPrevParameter],
    goto_next_comment: ['Goto next comment', un.gotoNextComment],
    goto_prev_comment: ['Goto previous comment', un.gotoPrevComment],
    goto_next_test: ['Goto next test', un.gotoNextTest],
    goto_prev_test: ['Goto previous test', un.gotoPrevTest],
    goto_next_entry: ['Goto next entry', un.gotoNextEntry],
    goto_prev_entry: ['Goto previous entry', un.gotoPrevEntry],
    goto_next_xml_element: ['Goto next (X)HTML element', un.gotoNextXmlElement],
    goto_prev_xml_element: ['Goto previous (X)HTML element', un.gotoPrevXmlElement],

    // ---- view / window / space ----
    align_view_center: ['Align view center', vw.alignViewCenter],
    align_view_top: ['Align view top', vw.alignViewTop],
    align_view_bottom: ['Align view bottom', vw.alignViewBottom],
    align_view_middle: ['Align view middle', vw.alignViewMiddle],
    rotate_view: ['Goto next window', vw.rotateView],
    hsplit: ['Horizontal bottom split', vw.hsplit],
    vsplit: ['Vertical right split', vw.vsplit],
    hsplit_new: ['Horizontal bottom split scratch buffer', vw.hsplitNew],
    vsplit_new: ['Vertical right split scratch buffer', vw.vsplitNew],
    transpose_view: ['Transpose splits', vw.transposeView],
    wclose: ['Close window', vw.wclose],
    wonly: ['Close windows except current', vw.wonly],
    jump_view_left: ['Jump to left split', vw.jumpViewLeft],
    jump_view_right: ['Jump to right split', vw.jumpViewRight],
    jump_view_up: ['Jump to split above', vw.jumpViewUp],
    jump_view_down: ['Jump to split below', vw.jumpViewDown],
    swap_view_left: ['Swap with left split', vw.swapViewLeft],
    swap_view_right: ['Swap with right split', vw.swapViewRight],
    swap_view_up: ['Swap with split above', vw.swapViewUp],
    swap_view_down: ['Swap with split below', vw.swapViewDown],
    goto_file_hsplit: ['Goto files in selections (hsplit)', vw.gotoFileHsplit],
    goto_file_vsplit: ['Goto files in selections (vsplit)', vw.gotoFileVsplit],
    file_picker: ['Open file picker', vw.filePicker],
    file_picker_in_current_directory: ['Open file picker at current working directory', vw.filePickerInCurrentDirectory],
    file_explorer: ['Open file explorer', vw.fileExplorer],
    file_explorer_in_current_buffer_directory: ['Open file explorer at current buffer directory', vw.fileExplorerInCurrentBufferDirectory],
    buffer_picker: ['Open buffer picker', vw.bufferPicker],
    jumplist_picker: ['Open jumplist picker', vw.jumplistPicker],
    symbol_picker: ['Open symbol picker', vw.symbolPicker],
    lsp_or_syntax_symbol_picker: ['Open symbol picker', vw.symbolPicker],
    workspace_symbol_picker: ['Open workspace symbol picker', vw.workspaceSymbolPicker],
    lsp_or_syntax_workspace_symbol_picker: ['Open workspace symbol picker', vw.workspaceSymbolPicker],
    diagnostics_picker: ['Open diagnostic picker', vw.diagnosticsPicker],
    workspace_diagnostics_picker: ['Open workspace diagnostic picker', vw.workspaceDiagnosticsPicker],
    changed_file_picker: ['Open changed file picker', vw.changedFilePicker],
    last_picker: ['Open last picker', vw.lastPicker],
    command_palette: ['Open command palette', vw.commandPalette],
    goto_definition: ['Goto definition', vw.gotoDefinition],
    goto_declaration: ['Goto declaration', vw.gotoDeclaration],
    goto_type_definition: ['Goto type definition', vw.gotoTypeDefinition],
    goto_reference: ['Goto references', vw.gotoReference],
    goto_implementation: ['Goto implementation', vw.gotoImplementation],
    hover: ['Show docs for item under cursor', vw.hover],
    rename_symbol: ['Rename symbol', vw.renameSymbol],
    code_action: ['Perform code action', vw.codeAction],
    completion: ['Invoke completion popup', vw.completion],
    signature_help: ['Show signature help', vw.signatureHelp],
    select_references_to_symbol_under_cursor: ['Select symbol references', vw.selectReferencesToSymbolUnderCursor],
    toggle_comments: ['Comment/uncomment selections', vw.toggleComments],
    toggle_line_comments: ['Line comment/uncomment selections', vw.toggleLineComments],
    toggle_block_comments: ['Block comment/uncomment selections', vw.toggleBlockComments],
    dap_launch: ['Launch debug target', vw.dapLaunch],
    dap_restart: ['Restart debugging session', vw.dapRestart],
    dap_toggle_breakpoint: ['Toggle breakpoint', vw.dapToggleBreakpoint],
    dap_continue: ['Continue program execution', vw.dapContinue],
    dap_pause: ['Pause program execution', vw.dapPause],
    dap_step_in: ['Step in', vw.dapStepIn],
    dap_step_out: ['Step out', vw.dapStepOut],
    dap_next: ['Step to next', vw.dapNext],
    dap_variables: ['List variables', vw.dapVariables],
    dap_terminate: ['End debug session', vw.dapTerminate],
    dap_edit_condition: ['Edit breakpoint condition on current line', vw.dapEditCondition],
    dap_edit_log: ['Edit breakpoint log message on current line', vw.dapEditLog],
    dap_switch_thread: ['Switch current thread', vw.dapSwitchThread],
    dap_switch_stack_frame: ['Switch stack frame', vw.dapSwitchStackFrame],
    dap_enable_exceptions: ['Enable exception breakpoints', vw.dapEnableExceptions],
    dap_disable_exceptions: ['Disable exception breakpoints', vw.dapDisableExceptions],

    // ---- shell ----
    shell_pipe: ['Pipe selections through shell command', sh.shellPipe],
    shell_pipe_to: ['Pipe selections into shell command ignoring output', sh.shellPipeTo],
    shell_insert_output: ['Insert shell command output before selections', sh.shellInsertOutput],
    shell_append_output: ['Append shell command output after selections', sh.shellAppendOutput],
    shell_keep_pipe: ['Filter selections with shell predicate', sh.shellKeepPipe],

    // ---- insert mode ----
    delete_char_backward: ['Delete previous char', ins.deleteCharBackward],
    delete_char_forward: ['Delete next char', ins.deleteCharForward],
    delete_word_backward: ['Delete previous word', ins.deleteWordBackward],
    delete_word_forward: ['Delete next word', ins.deleteWordForward],
    kill_to_line_start: ['Delete till start of line', ins.killToLineStart],
    kill_to_line_end: ['Delete till end of line', ins.killToLineEnd],
    insert_newline: ['Insert newline', ins.insertNewline],
    insert_tab: ['Insert tab char', ins.insertTab],
    smart_tab: ['Insert tab if all cursors have all whitespace to their left; otherwise, run a separate command.', ins.smartTab],

    // ---- misc ----
    command_mode: ['Enter command mode', async (cx) => cx.engine.runTyped?.('', cx)],
    no_op: ['Do nothing', () => {}],
  };

  engine.registerAll(table);

  // Insert-mode arrow/page/home/end keys reuse VS Code cursor movement so
  // soft-wrap and folding behave natively.
  const insertOverrides: Table = {
    move_visual_line_up: ['Move up', ins.insertModeMoveUp],
    move_visual_line_down: ['Move down', ins.insertModeMoveDown],
    move_char_left: ['Move left', ins.insertModeMoveLeft],
    move_char_right: ['Move right', ins.insertModeMoveRight],
    page_up: ['Page up', ins.insertModePageUp],
    page_down: ['Page down', ins.insertModePageDown],
    goto_line_start: ['Line start', ins.insertModeHome],
    goto_line_end_newline: ['Line end', ins.insertModeEnd],
  };
  for (const [name, [doc, fn]] of Object.entries(insertOverrides)) {
    const normal = engine.commands.get(name)!;
    engine.register(name, doc, (cx) => (cx.mode === 'insert' ? fn(cx) : normal.fn(cx)));
  }
}
